# Generated by Django 4.2 on 2023-04-17 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 23, 59, 59, 436661), verbose_name='Дедлайн'),
        ),
    ]
