# Generated by Django 4.2 on 2023-04-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='ToDoItem',
        ),
    ]
